### ISSUE TITLE
`token` option is not working on Windows

### ISSUE THREAD

**Issue by CedX** [MrBoolean/gulp-codacy#1]
The plugin is not working on my side :( Every time, I get the following error:

```
Command failed: CODACY_PROJECT_TOKEN=<codacy-token> [...]\node_modules\.bin\codacy-coverage < "[...]\var\lcov.info"
```

Environment:
- Operating System: Windows 10
- Node.js: 6.2.1
- Gulp.js: 3.9.1
- Codacy plugin: 1.0.0

On Windows, environment variables use a different syntax to be set on the command line. Like this:

```
set "CODACY_PROJECT_TOKEN=<codacy-token>" && [...]\node_modules\.bin\codacy-coverage < "[...]\var\lcov.info"
```

Could you improve your support of Windows platform? Thanks.

**Comment by m19c** [comment]
Nope. `gulp-codacy` is just a wrapper to reduce the code of your gulpfile. This means, that the error actually occurs in the module `codacy-coverage`.
